### ISSUE TITLE
[Task]: Implement REST Endpoint for Yaci-DevKit Instance Management

### ISSUE THREAD

**Issue by fabianbormann** [cardano-foundation/cardano-devkit#13]
### 📝 Task description

The Cardano DevKit backend requires a REST endpoint to manage Yaci-DevKit instances, particularly for spawning new instances for testing purposes. This endpoint should provide a way to create, list, and manage instances programmatically.
Rocket.rs should be used to provide the API. It should be possible to select the default, or active yaci-devkit.

### Component

cli

### Steps to complete

- [ ] Add a Rocket.rs based http interface to the devkit
- [ ] Implement endpoint to list instances
- [ ] Changing the default instance
- [ ] Bringing down a non-default instance
- [ ] Create a new instance
