### ISSUE TITLE
[Task]: Add Multi-Platform Distribution and Release Management

### ISSUE THREAD

**Issue by fabianbormann** [cardano-foundation/cardano-devkit#3]
### 📝 Task description

This issue aims to upload native binaries to a GitHub release, including binaries for Windows, Linux (Debian), and macOS. The goal is to come up with a workflow that automates the build and release process for these targets, leveraging the `release-please` workflow for seamless versioning and deployment.

### Component

package distribution

### Steps to complete

- [x] Create workflow file for building the rust app in a platform matrix
- [x] Trigger workflow with a condition automatically after a `release-please` release
- [x] Check if binaries are attached to a release, after running the workflow

**Comment by fabianbormann** [comment]
Workflow has been [implemented here](https://github.com/cardano-foundation/cardano-devkit/actions/workflows/publish.yml). 
<img width="968" alt="image" src="https://github.com/user-attachments/assets/73a98e12-d058-4af6-8d7a-775e304a94b4" />
