### ISSUE TITLE
[Task]: Simplify and Integrate Cardano Foundation Explorer

### ISSUE THREAD

**Issue by fabianbormann** [cardano-foundation/cardano-devkit#8]
### 📝 Task description

The Cardano Foundation Explorer needs to be simplified to interact with the Yaci Store and integrated into the CardanoDevKit. This will enhance the overall user experience by enabling the user to check the transactions, blocks, etc. of the local Cardano network.

### Component

explorer

### Steps to complete

- [ ] Rewrite the explorer backend to match with yaci-store's api
- [ ] Hide non-supported views
- [ ] Run the explorer aside the DevKit

### Additional context

- It would make sense to link the explorer from the tauri app, but maybe open a browser to access it, as an integration of a ui into an ui could become messy. 
- If already available at the time of this task completion, it would make sense to integrate the settings such as port, etc. into the config and therefore settings page of the tauri app
