### ISSUE TITLE
[Task]: Implement Service Settings Page in Tauri UI

### ISSUE THREAD

**Issue by fabianbormann** [cardano-foundation/cardano-devkit#9]
### 📝 Task description

The Tauri UI for the CardanoDevKit requires a new page to display and allow users to modify service settings from the config file. Additionally, a generic interface needs to be implemented to ensure seamless interaction between the config file and the UI, respecting the types and ranges of settings (e.g., int, bool, port range, etc.).

### Component

ui

### Steps to complete

- [ ] Get the current settings from the file over the Rust backend
- [ ] Align on a schema for the config file to include services, adjustable parameters that can be changed via cli but also provides type and range to make it adjustable in ui
- [ ] Add form elements to change ports, urls, enable or disable services (in case local or remote services want to be used instead)
- [ ] Play changes back from ui to the config file and restart services with applied settings
- [ ] Allow to "restore default" settings

### Additional context

Blocked by #7

**Comment by fabianbormann** [comment]
#7 has been done.
